from __future__ import annotations

import json
import re
import stat
from pathlib import Path
from typing import Any, Dict, List, Optional

from .errors import EvoTraceError
from .gitops import (
    copy_file,
    create_base_archive_binary,
    git,
    head_commit,
    require_repo,
)
from .quality import task_is_meaningful
from .store import Store, find_git_root
from .util import load_jsonl, unique, utc_now, write_json

VERIFY_PREFIXES = [
    re.compile(r"^(?:uv\s+run\s+)?(?:python(?:3(?:\.\d+)?)?\s+-m\s+)?pytest\b"),
    re.compile(r"^(?:uv\s+run\s+)?python(?:3(?:\.\d+)?)?\s+-m\s+unittest\b"),
    re.compile(r"^(?:uv\s+run\s+)?(?:ruff|mypy|pyright|tox|nox)\b"),
    re.compile(r"^(?:npm|pnpm|yarn|bun)\s+(?:test|run\s+(?:test|lint|build|typecheck))\b"),
    re.compile(r"^cargo\s+(?:test|check|clippy)\b"),
    re.compile(r"^go\s+test\b"),
    re.compile(r"^make\s+(?:test|check|lint)\b"),
    re.compile(r"^(?:mvn|mvnw|\.\/mvnw)\b.*\btest\b"),
    re.compile(r"^(?:gradle|\.\/gradlew)\s+(?:test|check)\b"),
]
REMOTE_COMMAND = re.compile(r"(?i)(?:^|[;&|]\s*)ssh(?:\s|$)")

SANDBOX_POLICY = {
    "schema_version": "0.1",
    "execution": "container_only",
    "host_repository": "read_only_source",
    "workspace": "ephemeral_container_copy",
    "host_mounts": [],
    "docker_socket": False,
    "privileged": False,
    "network": "none_by_default",
    "capabilities": "drop_all",
    "no_new_privileges": True,
    "host_output": "new_run_directory_only",
    "internal_access": "explicit_read_only_adapter_or_mock_only",
}


VERIFIER_SCRIPT = r'''#!/usr/bin/env python3
"""Generated by EvoTrace. This file is intentionally dependency-free."""
import argparse
import json
import os
import subprocess
import tempfile
import time
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    repo = args.repo.resolve()
    config = json.loads((Path(__file__).parent / "verifier.json").read_text())
    checks = []
    status = subprocess.run(
        ["git", "status", "--porcelain=v1"],
        cwd=repo,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    ignored_parts = {"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "node_modules", "target"}
    changed = []
    changed_paths = []
    for line in status.stdout.splitlines():
        path = line[3:].split(" -> ")[-1]
        if line.strip() and not any(part in ignored_parts for part in Path(path).parts):
            changed.append(line)
            changed_paths.append(path)
    with tempfile.TemporaryDirectory(prefix="evotrace-pycache-") as pycache:
        environment = os.environ.copy()
        environment["PYTHONPYCACHEPREFIX"] = pycache
        for command in config.get("commands", []):
            started = time.monotonic()
            try:
                result = subprocess.run(
                    command,
                    cwd=repo,
                    env=environment,
                    shell=True,
                    text=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    timeout=config.get("timeout_seconds", 600),
                )
                passed = result.returncode == 0
                output = result.stdout[-12000:]
                exit_code = result.returncode
            except subprocess.TimeoutExpired as exc:
                passed = False
                output = ((exc.stdout or "") + "\nTIMEOUT").strip()[-12000:]
                exit_code = 124
            checks.append({
                "name": command,
                "passed": passed,
                "exit_code": exit_code,
                "duration_seconds": round(time.monotonic() - started, 3),
                "output": output,
            })
    protected_modified = sorted(set(changed_paths) & set(config.get("protected_paths", [])))
    if config.get("protected_paths"):
        checks.append({
            "name": "protected tests were not modified",
            "passed": not protected_modified,
            "modified_paths": protected_modified,
            "output": "\n".join(protected_modified),
        })
    if config.get("require_change", True):
        checks.append({
            "name": "candidate changed the repository",
            "passed": bool(changed),
            "changed_entries": len(changed),
            "output": "\n".join(changed[:200]),
        })
    passed_count = sum(1 for check in checks if check["passed"])
    report = {
        "passed": bool(checks) and passed_count == len(checks),
        "score": round(passed_count / len(checks), 4) if checks else 0.0,
        "checks": checks,
        "changed_entries": len(changed),
    }
    print(json.dumps(report, indent=2) if args.json else format_report(report))
    raise SystemExit(0 if report["passed"] else 1)


def format_report(report):
    lines = []
    for check in report["checks"]:
        mark = "PASS" if check["passed"] else "FAIL"
        lines.append(f"[{mark}] {check['name']}")
        if not check["passed"] and check.get("output"):
            lines.append(check["output"][-2000:])
    lines.append(f"Score: {report['score'] * 100:.1f}%")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
'''


SETUP_SCRIPT = r"""#!/bin/sh
set -eu
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
DEST=${1:-"$PWD/workspace"}
if [ -e "$DEST" ] && [ "$(ls -A "$DEST" 2>/dev/null)" ]; then
  echo "Destination is not empty: $DEST" >&2
  exit 2
fi
mkdir -p "$DEST"
tar -xzf "$SCRIPT_DIR/environment/base.tar.gz" -C "$DEST"
git -C "$DEST" init -q
git -C "$DEST" config user.email evotrace@local
git -C "$DEST" config user.name EvoTrace
git -C "$DEST" add -A
git -C "$DEST" commit -q --allow-empty -m "EvoTrace base state"
if [ -s "$SCRIPT_DIR/patches/initial.patch" ]; then
  git -C "$DEST" apply --whitespace=nowarn "$SCRIPT_DIR/patches/initial.patch"
fi
if [ -s "$SCRIPT_DIR/environment/untracked-initial.tar.gz" ]; then
  tar -xzf "$SCRIPT_DIR/environment/untracked-initial.tar.gz" -C "$DEST"
fi
echo "$DEST"
"""


def commands_from_events(events_path: Path) -> List[str]:
    if not events_path.exists():
        return []
    candidates: List[str] = []
    for event in load_jsonl(events_path):
        if event.get("kind") != "tool.call":
            continue
        data = event.get("data") or {}
        arguments = data.get("arguments")
        if not isinstance(arguments, dict):
            continue
        command = arguments.get("cmd") or arguments.get("command")
        if not isinstance(command, str):
            continue
        # A verifier observed inside an SSH command belongs to the remote
        # machine, not to the locally reconstructed repository.
        if REMOTE_COMMAND.search(command):
            continue
        for segment in re.split(r"\n|&&|;", command):
            normalized = segment.strip()
            if normalized and any(pattern.search(normalized) for pattern in VERIFY_PREFIXES):
                candidates.append(normalized)
    return unique(candidates)[-5:]


def _default_commands(repo: Path) -> List[str]:
    if (repo / "pyproject.toml").exists() or (repo / "pytest.ini").exists():
        if (repo / "tests").exists():
            return ["python -m pytest -q"]
    package_json = repo / "package.json"
    if package_json.exists():
        try:
            package = json.loads(package_json.read_text(encoding="utf-8"))
            scripts = package.get("scripts") or {}
            if "test" in scripts:
                manager = "pnpm" if (repo / "pnpm-lock.yaml").exists() else "npm"
                return [f"{manager} test"]
        except (json.JSONDecodeError, OSError):
            pass
    if (repo / "Cargo.toml").exists():
        return ["cargo test"]
    if (repo / "go.mod").exists():
        return ["go test ./..."]
    if (repo / "Makefile").exists():
        makefile = (repo / "Makefile").read_text(encoding="utf-8", errors="ignore")
        if re.search(r"^test\s*:", makefile, re.MULTILINE):
            return ["make test"]
    return []


def _patch_paths(patch: Path) -> set[str]:
    if not patch.exists() or patch.stat().st_size == 0:
        return set()
    paths = set()
    text = patch.read_text(encoding="utf-8", errors="replace")
    for match in re.finditer(r"^diff --git a/(.+?) b/(.+)$", text, re.MULTILINE):
        paths.add(match.group(2).strip())
    return paths


def _protected_test_paths(repo: Path, commit: str, reference_patch: Path) -> List[str]:
    if not reference_patch.exists() or reference_patch.stat().st_size == 0:
        return []
    changed_by_reference = _patch_paths(reference_patch)
    tree = git(repo, "ls-tree", "-r", "--name-only", commit).splitlines()
    protected = []
    for value in tree:
        path = Path(value)
        name = path.name.lower()
        is_test = (
            any(part.lower() in {"test", "tests", "__tests__"} for part in path.parts)
            or name.startswith("test_")
            or name.endswith("_test.py")
            or ".test." in name
            or ".spec." in name
        )
        if is_test and value not in changed_by_reference:
            protected.append(value)
    return sorted(protected)


def infer_environment(
    repo: Path,
    *,
    commit: Optional[str] = None,
    verifier_commands: Optional[List[str]] = None,
) -> Dict[str, Any]:
    if commit:
        files = set(git(repo, "ls-tree", "--name-only", commit).splitlines())
    else:
        files = {item.name for item in repo.iterdir()}
    commands = verifier_commands or []
    needs_pytest = any(
        re.search(
            r"(?:^|\s)(?:python(?:3(?:\.\d+)?)?\s+-m\s+)?pytest\b",
            value,
        )
        for value in commands
    )
    needs_ruff = any(re.search(r"(?:^|\s)(?:uv\s+run\s+)?ruff\b", value) for value in commands)
    needs_mypy = any(re.search(r"(?:^|\s)(?:uv\s+run\s+)?mypy\b", value) for value in commands)
    needs_node = any(
        re.search(r"^(?:npm|pnpm|yarn|bun)\s+", value.strip()) for value in commands
    )
    uses_python = needs_pytest or needs_ruff or needs_mypy or any(
        re.search(r"(?:^|\s)(?:python|python3|uv\s+run)(?:\s|$)", value)
        for value in commands
    )
    has_python_project = bool("pyproject.toml" in files or "uv.lock" in files)
    has_node_project = "package.json" in files
    unsupported: List[str] = []
    if needs_node and not has_node_project:
        unsupported.append(
            "Node verifier commands were recovered, but package.json is absent from the base commit"
        )
    if any(value.strip().startswith("pnpm ") for value in commands) and "pnpm-lock.yaml" not in files:
        unsupported.append(
            "pnpm verifier commands were recovered, but pnpm-lock.yaml is absent from the base commit"
        )

    install: List[str] = []
    uv_project = "uv.lock" in files
    if uv_project:
        install.extend(
            [
                "python -m pip install --no-cache-dir uv",
                "uv sync --frozen",
            ]
        )
        verifier_packages = [
            package
            for required, package in (
                (needs_pytest, "pytest"),
                (needs_ruff, "ruff"),
                (needs_mypy, "mypy"),
            )
            if required
        ]
        if verifier_packages:
            install.append(
                "uv pip install --python /workspace/.venv/bin/python "
                + " ".join(verifier_packages)
            )
    requirement_files = sorted(
        value
        for value in files
        if re.fullmatch(r"requirements(?:[-_.][A-Za-z0-9_.-]+)?\.txt", value)
    )
    if not uv_project and ("pyproject.toml" in files or requirement_files or uses_python):
        if "requirements.txt" in files:
            install.append("python -m pip install --no-cache-dir -r requirements.txt")
        elif requirement_files:
            preferred = next(
                (
                    value
                    for value in requirement_files
                    if any(marker in value.lower() for marker in ("test", "dev", "public"))
                ),
                requirement_files[0],
            )
            install.append(f"python -m pip install --no-cache-dir -r {preferred}")
        elif "pyproject.toml" in files:
            install.append("python -m pip install --no-cache-dir -e .")
        if needs_pytest:
            install.append("python -m pip install --no-cache-dir pytest")
        if needs_ruff:
            install.append("python -m pip install --no-cache-dir ruff")
        if needs_mypy:
            install.append("python -m pip install --no-cache-dir mypy")

    if needs_node and has_node_project:
        if "pnpm-lock.yaml" in files:
            install.extend(["corepack enable", "pnpm install --frozen-lockfile"])
        elif "package-lock.json" in files:
            install.append("npm ci")
        else:
            install.append("npm install")

    if uses_python or has_python_project:
        kind = "python+node" if needs_node else "python"
        base_image = "node:22-bookworm-slim" if needs_node else "python:3.11-slim"
        return {
            "kind": kind,
            "base_image": base_image,
            "install_commands": unique(install),
            "uv_project": uv_project,
            "requirements": requirement_files,
            "unsupported_reasons": unique(unsupported),
        }
    if needs_node or has_node_project:
        return {
            "kind": "node",
            "base_image": "node:22-bookworm-slim",
            "install_commands": unique(install),
            "unsupported_reasons": unique(unsupported),
        }
    if "Cargo.toml" in files:
        return {
            "kind": "rust",
            "base_image": "rust:1-slim",
            "install_commands": ["cargo fetch"],
            "unsupported_reasons": unique(unsupported),
        }
    if "go.mod" in files:
        return {
            "kind": "go",
            "base_image": "golang:1.24",
            "install_commands": ["go mod download"],
            "unsupported_reasons": unique(unsupported),
        }
    return {
        "kind": "generic",
        "base_image": "debian:bookworm-slim",
        "install_commands": [],
        "unsupported_reasons": unique(unsupported),
    }


def _dockerfile(environment: Dict[str, Any], *, hidden_tests: bool = False) -> str:
    install = "\n".join(f"RUN {command}" for command in environment["install_commands"])
    hidden = ""
    if hidden_tests:
        hidden = """COPY patches/hidden-tests.patch /evotrace-hidden-tests.patch
RUN if [ -s /evotrace-hidden-tests.patch ]; then git apply --whitespace=nowarn /evotrace-hidden-tests.patch; fi && git add -A && git commit -q --allow-empty -m 'EvoTrace hidden verifier fixtures'
"""
    return f"""ARG BASE_IMAGE={environment["base_image"]}
FROM ${{BASE_IMAGE}} AS runtime
RUN apt-get update && apt-get install -y --no-install-recommends git python3 python3-venv && rm -rf /var/lib/apt/lists/*
RUN python3 -m venv /opt/evotrace-bootstrap
ENV PATH="/workspace/.venv/bin:/opt/evotrace-bootstrap/bin:${{PATH}}"
WORKDIR /workspace
COPY environment/base.tar.gz /tmp/base.tar.gz
RUN tar -xzf /tmp/base.tar.gz -C /workspace && git init -q && git config user.email evotrace@local && git config user.name EvoTrace && git add -A && git commit -q --allow-empty -m 'EvoTrace base state'
COPY patches/initial.patch /tmp/initial.patch
RUN if [ -s /tmp/initial.patch ]; then git apply --whitespace=nowarn /tmp/initial.patch; fi
COPY environment/untracked-initial.tar.gz /tmp/untracked-initial.tar.gz
RUN if [ -s /tmp/untracked-initial.tar.gz ]; then tar -xzf /tmp/untracked-initial.tar.gz -C /workspace; fi
{hidden}{install}
RUN mkdir -p /evotrace
COPY task.md verifier.py verifier.json sandbox-policy.json /evotrace/
RUN groupadd --gid 65532 evotrace && useradd --uid 65532 --gid 65532 --no-create-home evotrace && chown -R 65532:65532 /workspace /evotrace
ENV EVOTRACE_TASK_FILE=/evotrace/task.md EVOTRACE_WORKSPACE=/workspace SCALEVERIFIER_TASK_FILE=/evotrace/task.md SCALEVERIFIER_WORKSPACE=/workspace

FROM runtime AS validation-reference
COPY patches/reference.patch /evotrace/reference.patch
COPY environment/untracked-reference.tar.gz /evotrace/untracked-reference.tar.gz
RUN chown 65532:65532 /evotrace/reference.patch /evotrace/untracked-reference.tar.gz
USER 65532:65532
CMD ["/bin/sh"]

FROM runtime AS task
USER 65532:65532
CMD ["/bin/sh"]
"""


def _task_yaml(task_id: str, task: str, source: str, verifier_count: int) -> str:
    indented = "\n".join(f"  {line}" for line in task.splitlines())
    return f"""schema_version: "0.1"
id: {json.dumps(task_id)}
description: |-
{indented}
source: {json.dumps(source)}
verifier:
  path: verifier.py
  command_count: {verifier_count}
"""


def compile_session(
    session_id: str,
    *,
    task_override: Optional[str] = None,
    extra_commands: Optional[List[str]] = None,
    store: Optional[Store] = None,
) -> tuple[Path, Dict[str, Any]]:
    target_store = store or Store()
    target_store.initialize()
    session_dir, trajectory = target_store.load_session(session_id)
    task = (task_override or (trajectory.get("task") or {}).get("text") or "").strip()
    if not task_is_meaningful(task):
        raise EvoTraceError(
            "This session has no meaningful recoverable task; the imported text is empty or a placeholder."
        )

    repository = trajectory.get("repository") or {}
    root_value = repository.get("root")
    repo = find_git_root(Path(root_value)) if root_value else require_repo()
    if repo is None:
        raise EvoTraceError(
            "The source repository is unavailable. Run compile from a checkout or set the session repository root."
        )
    commit = repository.get("base_commit") or head_commit(repo)
    check_commit = git(repo, "rev-parse", "--verify", f"{commit}^{{commit}}", check=False).strip()
    if not check_commit:
        raise EvoTraceError(f"Base commit is not available in {repo}: {commit}")

    source_kind = str((trajectory.get("source") or {}).get("kind") or "")
    reconstruction = str(repository.get("reconstruction_confidence") or "none")
    if source_kind != "command" and reconstruction not in {"high", "medium"}:
        raise EvoTraceError(
            "Repository reconstruction confidence is "
            f"{reconstruction}; high or medium is required before building."
        )
    reference_patch = session_dir / "patches" / "final.patch"
    if not reference_patch.exists() or reference_patch.stat().st_size == 0:
        raise EvoTraceError("This session has no reconstructed reference patch.")

    explicit = list((trajectory.get("verification") or {}).get("commands") or [])
    commands = unique([*explicit, *(extra_commands or [])])
    inference = "explicit"
    if not commands:
        commands = commands_from_events(session_dir / "events.jsonl")
        inference = "trajectory"
    if not commands:
        commands = _default_commands(repo)
        inference = "repository"
    if not commands:
        raise EvoTraceError("No behavioral verification command could be reconstructed.")
    environment = infer_environment(repo, commit=commit, verifier_commands=commands)
    unsupported = environment.get("unsupported_reasons") or []
    if unsupported:
        raise EvoTraceError("Environment reconstruction failed: " + "; ".join(unsupported))
    if environment.get("uv_project"):
        commands = [re.sub(r"^uv\s+run\s+", "", command) for command in commands]
        commands = [
            re.sub(r"^python3(?=\s+-m\s+pytest\b)", "python", command)
            for command in commands
        ]
    elif environment.get("kind") in {"python", "python+node"}:
        commands = [re.sub(r"^uv\s+run\s+", "", command) for command in commands]

    bundle = target_store.benchmarks / trajectory["session_id"]
    if bundle.exists():
        raise EvoTraceError(f"Benchmark already exists: {bundle}")
    (bundle / "environment").mkdir(parents=True)
    (bundle / "patches").mkdir(parents=True)

    create_base_archive_binary(repo, commit, bundle / "environment" / "base.tar.gz")
    copy_file(session_dir / "patches" / "initial.patch", bundle / "patches" / "initial.patch")
    copy_file(session_dir / "patches" / "final.patch", bundle / "patches" / "reference.patch")
    copy_file(
        session_dir / "environment" / "untracked-initial.tar.gz",
        bundle / "environment" / "untracked-initial.tar.gz",
    )
    copy_file(
        session_dir / "environment" / "untracked-final.tar.gz",
        bundle / "environment" / "untracked-reference.tar.gz",
    )

    protected_paths = _protected_test_paths(repo, commit, bundle / "patches" / "reference.patch")
    if trajectory.get("source", {}).get("kind") == "command":
        reproducibility_confidence = "high"
    elif reconstruction in {"high", "medium"}:
        reproducibility_confidence = "medium"
    else:
        reproducibility_confidence = "low"
    verifier = {
        "schema_version": "0.1",
        "commands": commands,
        "command_source": inference,
        "timeout_seconds": 600,
        "require_change": True,
        "protected_paths": protected_paths,
        "warning": None
        if commands
        else "No behavioral verifier was inferred; only repository change is checked.",
    }
    manifest = {
        "schema_version": "0.1",
        "id": trajectory["session_id"],
        "compiled_at": utc_now(),
        "task": task,
        "source": {
            "session_id": trajectory["session_id"],
            "agent": (trajectory.get("source") or {}).get("agent"),
        },
        "repository": {
            "base_commit": commit,
            "origin": repository.get("origin"),
        },
        "environment": environment,
        "verifier": verifier,
        "reproducibility": {
            "base_tree": True,
            "initial_patch": (bundle / "patches" / "initial.patch").stat().st_size > 0,
            "untracked_snapshot": (bundle / "environment" / "untracked-initial.tar.gz")
            .stat()
            .st_size
            > 0,
            "reference_patch": (bundle / "patches" / "reference.patch").stat().st_size
            > 0,
            "reference_untracked_snapshot": (
                bundle / "environment" / "untracked-reference.tar.gz"
            ).stat().st_size
            > 0,
            "confidence": reproducibility_confidence,
            "repository_reconstruction": reconstruction,
        },
        "sandbox": SANDBOX_POLICY,
    }
    write_json(bundle / "task.json", manifest)
    write_json(bundle / "environment" / "environment.json", environment)
    write_json(bundle / "verifier.json", verifier)
    write_json(bundle / "sandbox-policy.json", SANDBOX_POLICY)
    (bundle / "task.md").write_text(task + "\n", encoding="utf-8")
    (bundle / "task.yaml").write_text(
        _task_yaml(trajectory["session_id"], task, trajectory["source"]["kind"], len(commands)),
        encoding="utf-8",
    )
    (bundle / "verifier.py").write_text(VERIFIER_SCRIPT, encoding="utf-8")
    (bundle / "setup.sh").write_text(SETUP_SCRIPT, encoding="utf-8")
    (bundle / "Dockerfile").write_text(_dockerfile(environment), encoding="utf-8")
    for executable in [bundle / "verifier.py", bundle / "setup.sh"]:
        executable.chmod(executable.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return bundle, manifest
